version: 2

updates:
  - package-ecosystem: cargo
    directories:
      - /
      - rsdiff
      - core
      - derive
      - graphs
      - macros
      - math
    schedule:
      interval: monthly
  - package-ecosystem: devcontainers
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
