version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /xtask
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /acme
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /core
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /derive
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /macros
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /crates/compilers
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /crates/conduits
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /crates/net
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /crates/pipelines
    schedule:
      interval: daily