version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /xtask
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /crates/acme
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /crates/clusters
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /crates/compilers
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /crates/conduits
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /crates/core
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /crates/gateways
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /crates/pipelines
    schedule:
      interval: daily