version: 2
updates:
  - package-ecosystem: cargo
    directory: "crates/acme"
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: "crates/core"
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: "crates/macros"
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: "crates/network"
    schedule:
      interval: daily