version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /acme
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /minis
    schedule:
      interval: daily
