[workspace.package]
authors = ["FL03 <jo3mccain@icloud.com> (https://github.com/FL03)"]
categories = ["mathematics", "science"]
description = "Acme aims to provide a solid foundation for developing robust machine-learning systems in Rust."
edition = "2021"
homepage = "https://github.com/FL03/acme/wikis"
keywords = ["acme", "autodiff", "mathematics", "tensor"]
license = "Apache-2.0"
repository = "https://github.com/FL03/acme"
readme = "README.md"
version = "0.3.1"
# version = "0.3.1-nightly"

[workspace]
default-members = [
    "acme"
]

exclude = [ 
    
]

members = [
    "acme", 
    "core",
    "derive",
    "graphs",
    "macros",
    "tensor",
    "exp/container",
    "exp/ndtensor",
]
resolver = "2"

[workspace.dependencies]
paste = "1"
strum = { features = ["derive"], version = "0.26" }
smart-default = "0.7"

[profile.dev]
codegen-units = 256
debug = true
debug-assertions = true
incremental = true
lto = false
panic = "unwind"
rpath = false
opt-level = 0
overflow-checks = true

[profile.release]
codegen-units = 16
debug = false
debug-assertions = false
incremental = false
lto = false
panic = "unwind"
rpath = false
opt-level = "z"
overflow-checks = false
