[package]
authors = ["FL03 <jo3mccain@icloud.com>"]
description = "A Rust library created to serve the Scattered-Systems Ecosystem"
edition = "2021"
license = "MIT"
name = "acme"
repository = "https://github.com/FL03/rustbox.git"
version = "0.1.0"

[lib]
bench = false
crate-type = ["cdylib", "rlib"]
test = true
name = "acme"

[[test]]
test = true
name = "standard"
path = "tests/standard.rs"

[dependencies]
bson = { features = ["chrono-0_4", "serde_with"], version = "2.2.0" }
chrono = "0.4.19"
futures = "0.3.21"
hyper = { features = ["full"], version = "0.14.18" }
rand = "0.8.5"
reqwest = "0.11.10"
serde = { features = ["derive"], version = "1.0.137" }
serde_json = "1.0.81"
tokio = { features = ["full"], version = "1.18.2" }
tower = "0.4.12"