[package]
authors = ["FL03 <jo3mccain@icloud.com> (https://gitlab.com)"]
categories = []
description = "Core primitives forming the foundation of acme, a complete peer-to-peer networking utility"
edition = "2021"
homepage = "https://gitlab.com/scsys/lib/crates/acme/-/wikis/home"
keywords = ["async", "scsys"]
license = "MIT"
name = "acme-core"
repository = "https://gitlab.com/scsys/lib/crates/acme"
version = "0.2.1" # TODO - Update cargo package version

[lib]
crate-type = ["cdylib", "rlib"]
test = true

[build-dependencies]

[dependencies]
serde = { features = ["derive"], version = "1.0.145" }
strum = { features = ["derive"], version = "0.24.1" }

