[package]
authors = [
    "FL03 <jo3mccain@icloud.com> (https://github.com/FL03)",
    "Scattered-Systems (https://github.com/scattered-systems)"
]
categories = ["network-programming"]
description = "A client library for the Scattered Systems Ecosystem"
edition = "2021"
homepage = "https://scattered-systems.github.io/acme"
keywords = ["async", "client", "blockchain", "scsys"]
license = "MIT"
name = "acme-core"
publish = true
repository = "https://github.com/scattered-systems/acme.git"
version = "0.2.1" # TODO - Update cargo package version

[lib]
crate-type = ["cdylib", "rlib"]
test = true

[dependencies]
clap = { features = ["derive"], version = "3.2.16" }
serde = { features = ["derive"], version = "1.0.141" }
serde_json = "1.0.82"
tokio = { features = ["full"], version = "1.20.1" }
tracing-subscriber = "0.3.14"

[dependencies.scsys]
features = ["full"]
optional = false
version = "0.1.9"