[package]
description = "acme"
name = "acme-core"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = []

wasm = []


[lib]
crate-type = ["cdylib", "rlib"]
test = true

[build-dependencies]

[dev-dependencies]

[dependencies]
anyhow.workspace = true
async-trait = "0.1"
futures = "0.3"
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
smart-default.workspace = true
tokio = { features = ["macros", "sync"], version = "1" }
tracing-subscriber = "0.3"

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]

[target.wasm32-unknown-unknown]

[target.wasm32-wasi]
