.cargo_test_template: &cargo_test

  only:
    - /^v[0-9]+(?:.[0-9]+)+$/ # regular expression
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/'
  stage: test
  script:
    - cargo test --all-features --release --verbose --jobs 1


stages:
  - test
  - deploy



stable:cargo:
  image: rustdocker/rust:stable
  <<: *cargo_test