.cargo_test_template: &cargo_test
  stage: testing
  script:
    - cargo test --all-features --release --verbose --jobs 1
  
stages:
  - testing

stable:cargo:
  image: rustdocker/rust:stable
  rules:
    - if: '$CI_COMMIT_BRANCH =~ latest | $CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/'
  <<: *cargo_test