[package]
authors = ["FL03 <jo3mccain@icloud.com>"]
description = "A Rust library created to serve the Scattered-Systems Ecosystem"
edition = "2021"
keywords = ["scsys", "blockchain", "toolkit"]
license = "MIT"
name = "acme"
readme = "README.md"
repository = "https://github.com/FL03/acme.git"
version = "0.1.16"

[features]
core = ["acme-core"]
default = ["core", "libp2p/default"]
full = ["core", "data", "macros", "network"]
data = ["acme-data"]
macros = ["acme-macros"]
network= ["acme-network"]

[lib]
bench = false
crate-type = ["cdylib", "rlib"]
test = true

[[test]]
name = "test"
path = "tests/test.rs"
test = true

[dependencies]
bson = { features = ["chrono-0_4", "serde_with"], version = "2.2.0" }
chrono = "0.4.19"
config = "0.13.1"
futures = "0.3.21"
glob = "0.3.0"
libp2p = "0.45.1"

[dependencies.acme-core]
optional = true
version = "0.1.3"

[dependencies.acme-data]
optional = true
version = "0.1.3"

[dependencies.acme-macros]
optional = true
version = "0.1.3"

[dependencies.acme-network]
optional = true
version = "0.1.3"