[package]
authors = ["FL03 <jo3mccain@icloud.com>"]
description = "Created in support of Acme, an all-in-one blockchain sdk"
edition = "2021"
keywords = ["api", "axum", "tokio", "restful"]
name = "acme-api"
readme = "README.md"
repository = "https://github.com/FL03/acme"
version = "0.1.0"

[dependencies]
acme = { features = ["full"], path = "../../lib/acme", version = ">=0.1.29" }
axum = { features = ["headers"], version = "0.5.9" }
bson = { features = ["chrono-0_4", "serde_with"], version = "2.3.0" }
config = "0.13.1"
serde = { features = ["derive"], version = "1.0.137" }
serde_json = "1.0.81"
tokio = { features = ["full"], version = "1.19.2" }
tower = { features = ["full"], version = "0.4.13" }
tower-http = { features = ["compression-br", "propagate-header", "sensitive-headers"], version = "0.3.4" }