[package]
authors = ["FL03 <jo3mccain@icloud.com>"]
description = "Created in support of Acme, an all-in-one blockchain sdk"
edition = "2021"
keywords = ["cli"]
name = "acme-cli"
readme = "README.md"
repository = "https://github.com/FL03/acme"
version = "0.1.0"

[dependencies]
acme = { features = ["full"], path = "../../lib/acme", version = ">=0.1.29" }
bson = { features = ["chrono-0_4", "serde_with"], version = "2.3.0" }
clap = { features = ["derive"], version = "3.2.7" }
config = "0.13.1"
serde = { features = ["derive"], version = "1.0.137" }
serde_json = "1.0.81"