[package]
authors = ["FL03 <jo3mccain@icloud.com>", "Joe McCain III <jo3mccain@scattered-systems.com>"]
description = "A Rust library created to serve the Scattered-Systems Ecosystem"
edition = "2021"
keywords = ["blockchain", "cli", "cryptography", "scsys"]
license = "MIT"
name = "acme"
readme = "README.md"
repository = "https://github.com/FL03/acme.git"
version = "0.1.27" # TODO - Update crate version

[[bin]]
name = "acme-cli"
path = "src/main.rs"

[features]
chains = ["acme-chains"]
core = ["acme-core"]
data = ["acme-data"]
default = ["chains", "core", "data"]
derive = ["acme-derive"]
full = ["default", "derive", "macros", "network"]
macros = ["acme-macros"]
network = ["acme-network"]

[lib]
bench = false
crate-type = ["cdylib", "rlib"]
name = "acme"
path = "lib/lib.rs"
test = true

[[test]]
name = "test"
path = "tests/test.rs"
test = true

[dependencies]
clap = { features = ["derive"], version = "3.2.5" }
config = "0.13.1"
glob = "0.3.0"
serde = { features = ["derive"], version = "1.0.137" }

[dependencies.acme-chains]
optional = true
path = "../chains"
version = ">=0.1.0"

[dependencies.acme-core]
optional = true
path = "../core"
version = ">=0.1.10"

[dependencies.acme-data]
optional = true
path = "../data"
version = ">=0.1.10"

[dependencies.acme-derive]
optional = true
path = "../derive"
version = ">=0.1.0"

[dependencies.acme-macros]
optional = true
path = "../macros"
version = ">=0.1.10"

[dependencies.acme-network]
optional = true
path = "../network"
version = ">=0.1.10"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]