[package]
authors.workspace = true
categories = []
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords = ["async", "scsys"]
license.workspace = true
name = "acme"
publish = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[[example]]
name = "autodiff"
required-features = ["derive"]



[features]
default = ["core", "tensor"]
full = [
    "core",
    "derive",
    "macros",
    "tensor"
]

core = [
    "dep:acme-core"
]

derive = [
    "dep:acme-derive",
    "macros"
]

macros = [
    "dep:acme-macros"
]

tensor = [
    "dep:acme-tensor"
]

[lib]
bench = true
crate-type = ["cdylib", "rlib"]
doctest = true
test = true

[build-dependencies]

[dependencies]
acme-core = { features = [], optional = true, path = "../core", version = "0.3.0" }
acme-derive = { features = [], optional = true, path = "../derive", version = "0.3.0" }
acme-macros = { features = [], optional = true, path = "../macros", version = "0.3.0" }
acme-tensor = { features = [], optional = true, path = "../tensor", version = "0.3.0" }

[dev-dependencies]

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]

[target.wasm32-unknown-unknown]

[target.wasm32-wasi]
