[package]
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "acme"
readme.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = [
    "core",
    "tensor",
]

full = [
    "core",
    "derive",
    "graph",
    "serde",
    "tensor"
]

core = []

derive = [
    "dep:acme-derive",
    "macros"
]

graph = [
    "dep:acme-graphs"
]

io = [
    "acme-tensor/io"
]

macros = [
    "dep:acme-macros"
]

serde = [
    "acme-core/serde",
    "acme-graphs/serde",
    "acme-tensor/serde"
]

std = [
    "acme-core/std",
    "acme-tensor/std"
]

tensor = [
    "dep:acme-tensor"
]




[lib]
bench = true
crate-type = ["cdylib", "rlib"]
doctest = true
test = true

[[bench]]
name = "tensor"
required-features = ["tensor"]

[[example]]
doc = true
name = "autodiff"
required-features = ["macros"]

[[example]]
name = "graph"
required-features = ["graph"]

[[example]]
name = "macros"
required-features = ["macros"]


[[test]]
name = "macros"
required-features = ["macros"]


[build-dependencies]

[dependencies]
acme-core = { path = "../core", version = "0.3.1" }
acme-derive = { optional = true, path = "../derive", version = "0.3.1" }
acme-graphs = { optional = true, path = "../graphs", version = "0.3.1" }
acme-macros = { optional = true, path = "../macros", version = "0.3.1" }
acme-tensor = { optional = true, path = "../tensor", version = "0.3.1" }
# acme-core = { path = "../core", version = "0.3.1-nightly" }
# acme-derive = { optional = true, path = "../derive", version = "0.3.1-nightly" }
# acme-graphs = { optional = true, path = "../graphs", version = "0.3.1-nightly" }
# acme-macros = { optional = true, path = "../macros", version = "0.3.1-nightly" }
# acme-tensor = { optional = true, path = "../tensor", version = "0.3.1-nightly" }

[dev-dependencies]
approx = "0.5"
lazy_static = "1"
num = "0.4"
rand = "0.8"

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]

[target.wasm32-unknown-unknown]

[target.wasm32-wasi]
