[package]
authors = ["FL03 <jo3mccain@icloud.com> (https://gitlab.com)"]
categories = []
description = "A client library for the Scattered Systems Ecosystem"
edition = "2021"
homepage = "https://gitlab.com/scsys/lib/crates/acme/-/wikis/home"
keywords = ["async", "scsys"]
license = "MIT"
name = "acme"
publish = true
readme = "README.md"
repository = "https://gitlab.com/scsys/lib/crates/acme"
version = "0.2.1" # TODO - Update cargo package version

[lib]
crate-type = ["cdylib", "rlib"]
test = true

[features]
default = ["core", "minis"]
full = ["core", "derive", "macros", "minis"]

core = ["acme-core"]
derive = ["acme-derive"]
macros = ["acme-macros"]
minis = ["acme-minis"]

[build-dependencies]

[dependencies]


acme-core = { optional = true, path = "../core", version = "0.2.1"}
acme-derive = { optional = true, path = "../derive", version = "0.2.1" }
acme-macros = { optional = true, path = "../macros", version = "0.2.1" }
acme-minis = { optional = true, path = "../minis", version = "0.2.1"}



