[package]
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "acme"
readme.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = [
    "core",
    "math",
    "graph",
]

full = [
    "default",
    "derive",
    "serde",
    "trace",
]

core = []

derive = [
    "dep:acme-derive",
    "macros"
]

graph = [
    "dep:acme-graphs"
]

macros = [
    "dep:acme-macros"
]

math = [
    "dep:acme-math"
]

serde = [
    "acme-core/serde",
    "acme-graphs/serde",
]

std = [
    "acme-core/std",
    "acme-graphs/std",
]


trace = [
    "acme-core/trace",
    "acme-graphs/trace",
]

wasi = [
    "acme-core/wasi",
    "acme-graphs/wasi",
]

wasm = [
    "acme-core/wasm",
    "acme-graphs/wasm",
]



[lib]
bench = true
crate-type = ["cdylib", "rlib"]
doctest = true
test = true


[[example]]
doc = true
name = "autodiff"
required-features = ["macros"]

[[example]]
name = "graph"
required-features = ["graph"]

[[example]]
name = "macros"
required-features = ["macros"]


[[test]]
name = "macros"
required-features = ["macros"]


[build-dependencies]

[dependencies]
acme-core = { path = "../core", version = "0.3.2" }
acme-derive = { optional = true, path = "../derive", version = "0.3.2" }
acme-graphs = { optional = true, path = "../graphs", version = "0.3.2" }
acme-macros = { optional = true, path = "../macros", version = "0.3.2" }
acme-math = { optional = true, path = "../math", version = "0.3.2" }

# acme-core = { path = "../core", version = "0.3.2-nightly" }
# acme-derive = { optional = true, path = "../derive", version = "0.3.2-nightly" }
# acme-graphs = { optional = true, path = "../graphs", version = "0.3.2-nightly" }
# acme-macros = { optional = true, path = "../macros", version = "0.3.2-nightly" }
# acme-math = { optional = true, path = "../math", version = "0.3.2-nightly" }

[dev-dependencies]
approx = "0.5"
lazy_static = "1"
num = "0.4"
rand = "0.8"

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]

[target.wasm32-unknown-unknown]

[target.wasm32-wasi]
