[package]
authors.workspace = true
categories = []
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords = ["async", "scsys"]
license.workspace = true
name = "acme"
publish = true
readme.workspace = true
repository.workspace = true
version.workspace = true



[features]
default = ["core"]
full = [
    "agents",
    "core",
    "derive",
    "macros",
]

agents = [
    "acme-agents"
]

core = [
    "acme-core"
]

derive = [
    "acme-derive"
]

macros = [
    "acme-macros"
]

[lib]
bench = true
crate-type = ["cdylib", "rlib"]
doctest = true
test = true

[build-dependencies]

[dependencies]
acme-agents = { features = [], optional = true, path = "../agents", version = "0.3.0" }
acme-core = { features = [], optional = true, path = "../core", version = "0.3.0" }
acme-derive = { features = [], optional = true, path = "../derive", version = "0.3.0" }
acme-macros = { features = [], optional = true, path = "../macros", version = "0.3.0" }

[dev-dependencies]

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]

[target.wasm32-unknown-unknown]

[target.wasm32-wasi]
