[package]
categories = []
keywords = ["async", "scsys"]
name = "acme"
publish = true

authors.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]
test = true

[features]
default = ["core"]
full = [
    "core",
    "derive",
    "extras", 
    "macros",
    "net",
]
api = []
cli = [
    "clap/default",
    "clap/cargo",
    "clap/derive",
    "clap/env"
]

core = ["acme-core"]
derive = ["acme-derive/default"]
macros = ["acme-macros/default"]
extras = []


net = ["acme-net"]
wasm = ["acme-wasm/default"]

[build-dependencies]

[dependencies]
async-trait = "0.1"
axum-core = { optional = true, version = "0.3"}
clap = { features = ["cargo", "derive", "env"], optional = true, version = "4" }
scsys.workspace = true
serde.workspace = true
serde_json.workspace = true

acme-core = { features = [], optional = true, path = "../core", version = "0.2.6" }
acme-derive = { features = [], optional = true, path = "../derive", version = "0.2.6" }
acme-macros = { features = [], optional = true, path = "../macros", version = "0.2.6" }
acme-net = { features = [], optional = true, path = "../net", version = "0.2.6" }
acme-wasm = { features = [], optional = true, path = "../wasm", version = "0.2.6" }


[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]

[target.wasm32-unknown-unknown]

[target.wasm32-wasi]
