[package]
authors = ["FL03 <jo3mccain@icloud.com>", "Joe McCain III <jo3mccain@scattered-systems.com>"]
description = "A Rust library created to serve the Scattered-Systems Ecosystem"
edition = "2021"
keywords = ["blockchain", "cli", "cryptography", "scsys"]
license = "MIT"
name = "acme"
readme = "README.md"
repository = "https://github.com/FL03/acme.git"
version = "0.1.26" # TODO - Current Release v0.1.25

[[bin]]
name = "acme-cli"
path = "bin/main.rs"

[features]
core = ["acme-core"]
data = ["acme-data"]
default = ["core", "data"]
derive = ["acme-derive"]
full = ["default", "derive", "macros", "network"]
macros = ["acme-macros"]
network = ["acme-network"]

[lib]
bench = false
crate-type = ["cdylib", "rlib"]
test = true

[[test]]
name = "test"
path = "tests/test.rs"
test = true

[dependencies]
bson = { features = ["chrono-0_4", "serde_with"], version = "2.3.0" }
chrono = "0.4.19"
clap = { features = ["derive"], version = "3.2.5" }
config = "0.13.1"
serde = { features = ["derive"], version = "1.0.137" }
tokio = { features = ["full"], version = "1.19.2" }
tower = "0.4.13"
tracing = "0.1.35"
tracing-subscriber = "0.3.11"

[dependencies.acme-core]
optional = true
path = "../core"
version = ">=0.1.10"

[dependencies.acme-data]
optional = true
path = "../data"
version = ">=0.1.10"

[dependencies.acme-derive]
optional = true
path = "../derive"
version = ">=0.1.0"

[dependencies.acme-macros]
optional = true
path = "../macros"
version = ">=0.1.10"

[dependencies.acme-network]
optional = true
path = "../network"
version = ">=0.1.10"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]