version: "3.9"
services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - database
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - /data:/data

  context:
    container_name: context
    image: photon
    ports:
      - "8080:8080"
    restart: always

  database:
    container_name: database
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - /data/database:/var/lib/postgresql/data

volumes:
  app:
  data: