version: "3.9"
services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - cache
      - database
    ports:
      - "5432:5432"
      - "6379:6379"
      - "9097:9097"
      - "9098:9098"
      - "9099:9099"
    restart: always
    volumes:
      - /data/app:/data/app:cached
      - /data:/data

  cache:
    container_name: cache
    image: redis
    ports:
      - "6379:6379"
    restart: always

  database:
    container_name: database
    environment:
      POSTGRES_DB: appdata
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: example
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - /data/database:/var/lib/postgresql/data

volumes:
  app:
  data: