[package]
authors = ["FL03 <jo3mccain@icloud.com>", "Joe McCain III <jo3mccain@scattered-systems.com>"]
description = "Procedural macros created to support Acme, an all-in-one blockchain toolkit"
edition = "2021"
keywords = ["blockchain", "proc-macros", "scsys"]
license = "MIT"
name = "acme-macros"
readme = "README.md"
repository = "https://github.com/FL03/acme"
version = "0.1.13" # TODO - Update cargo package version

[lib]
bench = false
proc-macro = true
test = true


[[test]]
name = "test"
path = "tests/test.rs"
test = true

[dependencies]