[package]
authors = ["FL03 <jo3mccain@icloud.com>", "Joe McCain III <jo3mccain@scattered-systems.com>"]
description = "Procedural macros created to support Acme, an all-in-one blockchain toolkit"
edition = "2021"
keywords = ["blockchain", "proc-macros", "scsys"]
name = "acme-macros"
license = "MIT"
repository = "https://github.com/FL03/acme"
version = "0.1.12" # TODO - Current Release v0.1.11

[lib]
bench = false
proc-macro = true
test = true


[[test]]
name = "test"
path = "tests/test.rs"
test = true

[dependencies]
