[package]
authors.workspace = true
categories.workspace = true
description = "Acme is a complete development toolkit for extending platform functionality"
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "acme-macros"
readme.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = []

[lib]
crate-type = ["cdylib", "rlib"]
test = true

[build-dependencies]

[dependencies]
syn = { features = [], version = "2" }

[dev-dependencies]

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]

[target.wasm32-unknown-unknown]

[target.wasm32-wasi]
