[package]
authors = ["FL03 <jo3mccain@icloud.com>", "Joe McCain III <jo3mccain@scattered-systems.com>"]
description = "Procedural macros created to support Acme, an all-in-one blockchain toolkit"
edition = "2021"
keywords = ["blockchain", "proc-macros", "scsys"]
license = "MIT"
name = "acme-macros"
readme = "README.md"
repository = "https://github.com/FL03/acme"
version = "0.1.14" # TODO - Update cargo package version

[lib]
proc-macro = true
test = true


[[test]]
name = "test"
path = "tests/test.rs"
test = true

[dependencies]
proc-macro2 = ">=1.0.40"
quote = ">=1.0.20"
syn = { features = ["full"], version = ">=1.0.98" }

[dev-dependencies.acme]
path = "../acme"