[package]
authors = ["FL03 <jo3mccain@icloud.com>"]
description = "Core package of Acme, an all-in-one developer toolkit targetting decentralized environments"
edition = "2021"
keywords = ["blockchain", "toolkit"]
license = "MIT"
name = "acme-core"
readme = "README.md"
repository = "https://github.com/FL03/acme/crates/core"
version = "0.1.1"

[lib]
bench = false
crate-type = ["cdylib", "rlib"]
test = true

[[test]]
name = "test"
path = "tests/test.rs"
test = true

[dependencies]
