[package]
authors = ["FL03 <jo3mccain@icloud.com>"]
categories = ["blockchain", "peer-to-peer", "toolkit"]
description = "A Rust library created to serve the Scattered-Systems Ecosystem"
edition = "2021"
keywords = ["scsys", "blockchain", "toolkit"]
license = "MIT"
name = "acme"
repository = "https://github.com/FL03/acme.git"
version = "0.1.12"

[features]
# Include nothing by default
default = []

macros = ["acme-macros"]
#network = ["acme-network"]

[lib]
bench = false
crate-type = ["cdylib", "rlib"]
test = true

[[test]]
name = "test"
path = "tests/test.rs"
test = true

[dependencies]
blake2 = "0.10.4"
bson = { features = ["chrono-0_4", "serde_with"], version = "2.2.0" }
chrono = "0.4.19"
config = "0.13.1"
futures = "0.3.21"
glob = "0.3.0"
hex = "0.4.3"
hyper = { features = ["full"], version = "0.14.19" }
libp2p = { features = ["dns-tokio", "gossipsub", "mdns", "tcp-tokio"], version = "0.45.1" }
log = "0.4.17"
once_cell = "1.12.0"
pretty_env_logger = "0.4.0"
serde = { features = ["derive"], version = "1.0.137" }
serde_json = "1.0.81"
sha2 = "0.10.2"
tokio = { features = ["full"], version = "1.18.2" }
tracing = "0.1.34"
tracing-subscriber = "0.3.11"

[dependencies.acme-macros]
optional = true
version = "0.1.1"

#[dependencies.acme-network]
#optional = true
#version = "0.1.0"