name: Crates

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  CARGO_PREFIX: ${{ github.event.repository.name }}
  CARGO_TERM_COLOR: always

on:
  release:
    types: [ created ]
  repository_dispatch:
    types: [ publish ]
  workflow_dispatch:

jobs:
  core:
    name: Publish (core)
    runs-on: ubuntu-latest
    env:
      CARGO_PACKAGE_NAME: ${{ github.event.repository.name }}-core
    steps:
      - uses: actions/checkout@v4
      - name: Publish (${{ env.CARGO_PACKAGE_NAME }})
        run: cargo publish --all-features -v -p ${{ env.CARGO_PACKAGE_NAME }} --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
  features:
    name: Publish (sdk)
    needs: core
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features: [ derive, graphs, macros, tensor ]
    env:
      CARGO_PACKAGE_NAME: ${{ github.event.repository.name }}-${{ matrix.features }}
    steps:
      - uses: actions/checkout@v4
      - name: Publish (${{ env.CARGO_PACKAGE_NAME }})
        run: cargo publish --all-features -v -p ${{ env.CARGO_PACKAGE_NAME }} --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
  publish:
    name: Publish (${{ github.repository.name }})
    needs: features
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish (${{ github.event.repository.name }})
        run: cargo publish --all-features -v -p ${{ github.event.repository.name }} --token ${{ secrets.CARGO_REGISTRY_TOKEN }}