name: Crates

on:
  push:
    branches: [ "master", "latest" ]
  pull_request:
    branches: [ "latest" ]

env:
  PROJECT_SLUG: acme
  CARGO_TERM_COLOR: always
  CARGO_PKG_VERSION: 0.1.10

jobs:
  acme-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login
        run: cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Test
        run: cargo test -p acme-core
      - name: Build and Push
        run: cargo publish -p acme-core
  acme-derive:
    env:
      CARGO_PKG_NAME: acme-derive
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login
        run: cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Test
        run: cargo test -p $CARGO_PKG_NAME -v --color $CARGO_TERM_COLOR
      - name: Build and Push
        run: cargo publish -p $CARGO_PKG_NAME --all-features
  acme-macros:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login
        run: cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Test
        run: cargo test --package acme-macros
      - name: Build and Push
        run: cargo publish --package acme-macros
  acme-network:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login
        run: cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Test
        run: cargo test --package acme-network
      - name: Build and Push
        run: cargo publish --package acme-network