name: Crates

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  CARGO_TERM_COLOR: always

on:
  release:
    types: [ created ]
  repository_dispatch:
    types: [ publish ]
  workflow_dispatch:

jobs:
  core:
    name: Publish (core)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features: [ core ]
    steps:
      - uses: actions/checkout@v4
      - name: Publish (${{ github.ref.name }}-${{ matrix.features }})
        run: cargo publish --all-features -v -p ${{ github.ref.name }}-${{ matrix.features }} --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
  sdk:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-sdk
      cancel-in-progress: false
    name: Publish (sdk)
    needs: core
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features: [ derive, macros, tensor ]
    steps:
      - uses: actions/checkout@v4
      - name: Publish (${{ github.ref.name }}-${{ matrix.features }})
        run: cargo publish --all-features -v -p ${{ github.ref.name }}-${{ matrix.features }} --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
  publish:
    name: Publish (${{ github.ref.name }})
    needs: sdk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish (${{ github.ref.name }})
        run: cargo publish --all-features -v -p ${{ github.ref.name }} --token ${{ secrets.CARGO_REGISTRY_TOKEN }}