name: Rust

on:
  push:
    branches: [ "master" ]
    tags: [ "latest" ]
  pull_request:
    branches: [ "master" ]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login
        run: cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: cargo test --all-features --verbose --color always
  acme:
    needs: [ login ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        run: cargo publish --package acme --all-features --token ${{ secrets.CARGO_REGISTRY_TOKEN }} --verbose
  chains:
    needs: [ login ]
    runs-on: ubuntu-latest
    steps:
      - name: Publish
        run: cargo publish --package acme-chains --token ${{ secrets.CARGO_REGISTRY_TOKEN }} --verbose
  core:
    needs: [ login ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        run: cargo publish --package acme-core--token ${{ secrets.CARGO_REGISTRY_TOKEN }} --verbose
  data:
    needs: [ login ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        run: cargo publish --package acme-data --token ${{ secrets.CARGO_REGISTRY_TOKEN }} --verbose
  derive:
    needs: [ login ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        run: cargo publish --package acme-derive --token ${{ secrets.CARGO_REGISTRY_TOKEN }} --verbose
  macros:
    needs: [ login ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        run: cargo publish --package acme-macros --token ${{ secrets.CARGO_REGISTRY_TOKEN }} --verbose
  network:
    needs: [ login ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        run: cargo publish --package acme-network --token ${{ secrets.CARGO_REGISTRY_TOKEN }} --verbose
  sdk:
    needs: [ login, test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        run: cargo publish --package acme-sdk --all-features --token ${{ secrets.CARGO_REGISTRY_TOKEN }} --verbose