name: Rust

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  CARGO_TERM_COLOR: always

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    tags: [ nightly*, v*.*.* ]
  release:
  repository_dispatch:
    types: [ rust ]
  schedule:
    - cron: "30 21 * * 0" # Every Sunday at 21:30 UTC
  workflow_dispatch:

jobs:
  build:
    name: Build
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        toolchain: [ stable, nightly ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: setup (langspace)
        run: |
          rustup update
          rustup default ${{ matrix.toolchain }}
      - name: Build
        id: rust-build
        run: cargo build --features full -r -v --workspace
      - name: Cache build
        id: rust-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target/release
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
  test:
    name: Test
    strategy:
      matrix:
        toolchain: [ nightly ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1 #@v1
        with:
          override: true
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
      - name: Test
        id: rust-test
        run: cargo test --all-features -r -v --workspace
  bench:
    name: Bench
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup (langspace)
        run: |
          rustup update
          rustup default nightly
      - name: Bench
        id: rust-bench
        run: cargo bench --features full -v --workspace