name: Rust

on:
  push:
    tags:
      - v*.*.*
  pull_request:
    tags:
      - v*.*.*

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login
        run: cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Workspace
        run: cargo test --all-features --color always --release --verbose --workspace
  core:
    env:
      CRATE: acme-core
    needs: [ login, test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        run: cargo publish --package $CRATE --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
  derive:
    env:
      CRATE: acme-derive
    needs: [ login, test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        run: cargo publish --package $CRATE --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
  macros:
    env:
      CRATE: acme-macros
    needs: [ login, test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        run: cargo publish --package $CRATE --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
  network:
    env:
      CRATE: acme-network
    needs: [ login, test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        run: cargo publish --package $CRATE --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
  crate:
    env:
      CRATE: acme
    if: ${{ always() }}
    needs: [ core, derive, login, macros, network, test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        run: cargo publish --package $CRATE --token ${{ secrets.CARGO_REGISTRY_TOKEN }}