[package]
authors = ["FL03 <jo3mccain@icloud.com>", "Joe McCain III <jo3mccain@scattered-systems.com>"]
categories = []
description = "Acme was created to be an all-in-one blockchain toolkit in support of the Scattered-Systems ecosystem"
edition = "2021"
keywords = ["blockchain", "scsys", "toolkit"]
license = "MIT"
name = "acme-cli"
publish = true
readme = "README.md"
repository = "https://github.com/FL03/acme.git"
version = "0.1.35" # TODO - Update cargo package version


[dependencies]
bson = { features = ["chrono-0_4", "serde_with"], version = "2.3.0" }
chrono = "0.4.19"
clap = { features = ["derive"], version = "3.2.8" }
config = "0.13.1"
glob = "0.3.0"
http = "0.2.8"
hyper = { features = ["full"], version = "0.14.19" }
reqwest = "0.11.11"
serde = { features = ["derive"], version = "1.0.138" }
serde_json = "1.0.82"


[dependencies.acme-sdk]
features = ["full"]
optional = true
version = ">=0.1.35"